# Generated by Django 3.1.3 on 2021-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=650, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('genre', models.CharField(max_length=60, verbose_name='Жанр')),
                ('author', models.CharField(max_length=35, verbose_name='Автор')),
                ('year', models.DateField(verbose_name='Год выпуска книги')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Добавление книги на сайт')),
            ],
            options={
                'verbose_name': 'Книжный магазин',
                'verbose_name_plural': 'Книжные магазины',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранная'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Задача'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
