# Generated by Django 3.1.3 on 2021-01-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210120_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksshop',
            name='year',
            field=models.DateTimeField(verbose_name='Год выпуска книги'),
        ),
    ]
