# Generated by Django 3.1.3 on 2021-01-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210120_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksshop',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранная'),
        ),
    ]
