# Generated by Django 3.1.3 on 2021-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booksshop_is_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksShop',
            new_name='BookShop',
        ),
    ]
